<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllOrdered()
    {
        $dql = "select cat from AppBundle\Entity\Category cat order  by cat.name desc";

        $query = $this->getEntityManager()->createQuery($dql);
//        var_dump($query->getSQL());

        return $query->execute();




    }
}
